package com.polk.genesis;

public enum EventTypeCode {

	AM_MEAL("AM MEAL", "BREAKFAST"), ATHLCOMP("ATHLCOMP", "ATHLETICCOMPETITIONS"), BLKHIST("BLKHIST",
			"BLACKHISTORYMONTHACTIVITY"), CEREMONY("CEREMONY", "RECOGNITIONCEREMONY"), CHILDCAR("CHILDCAR",
			"CHILDCARECLASSES"), CHS("CHS", "COLLEGIATEHIGHSCHOOL"), CONF("CONF", "CONFERENCE"), CONSTRUC("CONSTRUC",
			"UNDERCONSTRUCTION"), CORPCOLL("CORPCOLL", "CORPORATECOLLEGECLASS"), CULPERF("CULPERF",
			"CULTURALPERFORMANCE"), DANCE("DANCE", "DANCE"), DEMOLISH("DEMOLISH", "ROOMISTOBEDEMOLISHED"), DINNER(
			"DINNER", "DINNER"), ENRICH("ENRICH", "ACADEMICENRICHMENT"), EXAM("EXAM", "EXAMINATION"), EXHIBIT(
			"EXHIBIT", "GALLERYEXHIBIT"), FNDEVENT("FNDEVENT", "BACKONCAMPUS"), GALLERY("GALLERY", "EXHIBITOPENING"), GRAD(
			"GRAD", "GRADUATIONCEREMONY"), HHM("HHM", "HISPANICHERITAGEACTIVITY"), INDUCT("INDUCT",
			"PTKINDUCTIONCEREMONY"), LABTIME("LABTIME", "LABTIME"), LECTURE("LECTURE", "LECTURE"), LUNCH("LUNCH",
			"LUNCHEON"), MEETEXT("MEETEXT", "MEETING(NONPCCPERSONNEL)"), MEETING("MEETING", "MEETING(PCCPERSONNEL)"), OFFICEHR(
			"OFFICEHR", "OFFICEHOURS"), OPENHOUS("OPENHOUS", "OPENHOUSE"), ORIENTE("ORIENTE", "ORIENTATION"), ORIENTF(
			"ORIENTF", "FACULTYORIENTATION"), ORIENTS("ORIENTS", "STUDENTORIENTATION"), OUTDOOR("OUTDOOR",
			"OUTDOOREVENTS"), PDTC("PDTC", "PROFESSIONALDEVELOPMENT&TRAININGCENT"), PINNING("PINNING",
			"PINNINGCEREMONY"), PURGE("PURGE", "ROOMISPURGEDFROMINVENTORY"), RECEPT("RECEPT", "RECEPTION"), REGISTER(
			"REGISTER", "REGISTRATION"), REHEARSE("REHEARSE", "REHEARSAL"), REMODEL("REMODEL",
			"REMODELING-FACILITY/ROOM"), RENOVATE("RENOVATE", "ROOMRENOVATION"), REPAIRS("REPAIRS", "REPAIRS"), RESTRICT(
			"RESTRICT", "RESTRICTEDROOMUSE"), SEMINAR("SEMINAR", "SEMINAR"), SETUP("SET-UP", "SET-UPROOM"), SPEAKER(
			"SPEAKER", "GUESTSPEAKER"), STUCLUBS("STUCLUBS", "STUDENTCLUBACTIVITIES"), SUMCAMP("SUMCAMP", "SUMMERCAMP"), TESTING(
			"TESTING", "TESTING"), TRAINING("TRAINING", "TRAININGSESSION"), TUTORING("TUTORING", "TUTORING"), USF(
			"USF", "USFROOM"), WEB("WEB", "POSTONCOLLEGEWEBCALENDAR"), WELLNESS("WELLNESS", "EMPLOYEEWELLNESSCLASS"), WHM(
			"WHM", "WOMEN'SHISTORYMONTHACTIVITY"), WORKSHOP("WORKSHOP", "WORKSHOP");

	private String code;
	private String description;

	EventTypeCode(String code, String desc) {
		this.code = code;
		this.description = desc;
	}

	public String getCode() {
		return code;
	}

	public String getDescription() {
		return description;
	}

}
