package com.polk.genesis;

import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.List;

public class SoapBookingRequestBuilder {
	public String getSoapRequest(String siteLocalNumber, String facilityLocalNumber, String inventoryKey,
                                 String eventKey, EventTypeCode eventTypeCode, String eventTitle, Date eventStartDate, Date eventEndDate,
                                 int headCount, String scheduleStartTime, String scheduleEndTime, String currentRoomUsage) {

		// Validations
		if (eventKey.length() > 9) {
			throw new IllegalArgumentException("Event key can not be more than 9 characters.");
		}

		if (eventTitle.length() > 50) {
			throw new IllegalArgumentException("Event title can not be more than 50 characters.");
		}

		if (eventStartDate == null) {
			throw new IllegalArgumentException("Event start date can not be null.");
		}

		if (eventEndDate == null) {
			throw new IllegalArgumentException("Event end date can not be null.");
		}

		if (headCount < 1) {
			throw new IllegalArgumentException("Head count can not be zero or less.");
		}

		SimpleDateFormat sdf = new SimpleDateFormat("yyyyMMdd");

		StringBuilder sb = new StringBuilder();

		sb.append("<?xml version=\"1.0\" encoding=\"UTF-8\"  ?>");
		sb.append("<!-- Generated by Software AG, EntireX XML Mapping Editor (8.0.1.000) on 2015-10-28 at 09:21:54 -->");
		sb.append("<SOAP-ENV:Envelope xmlns:SOAP-ENC=\"http://schemas.xmlsoap.org/soap/encoding/\" xmlns:xsi=\"http://www.w3.org/2001/XMLSchema-instance\" xmlns:xmm=\"http://namespace.softwareag.com/entirex/xml/mapping\" xmlns:xsd=\"http://www.w3.org/2001/XMLSchema\" xmlns:SOAP-ENV=\"http://schemas.xmlsoap.org/soap/envelope/\">");
		sb.append("<SOAP-ENV:Header>");
		sb.append("<!-- <SOAPAction>KFR110N1</SOAPAction> -->");
		sb.append("</SOAP-ENV:Header>");
		sb.append("<SOAP-ENV:Body>");
		sb.append("<m:KFR110N1 xmlns:m=\"urn:com-softwareag-entirex-rpc:PROGDEV-KFR110N1\">");
		sb.append("<KFR110A1-INPUT>");

		sb.append("<EVENT-KEY>");
		sb.append(eventKey);
		sb.append("</EVENT-KEY>");

		sb.append("<EVENT-TYPE-CODE>");
		sb.append(eventTypeCode.getCode());
		sb.append("</EVENT-TYPE-CODE>");

		sb.append("<EVENT-TITLE>");
		sb.append(eventTitle);
		sb.append("</EVENT-TITLE>");

		sb.append("<EVENT-START-DATE>");
		sb.append(sdf.format(eventStartDate));
		sb.append("</EVENT-START-DATE>");

		sb.append("<EVENT-END-DATE>");
		sb.append(sdf.format(eventEndDate));
		sb.append("</EVENT-END-DATE>");

		sb.append("<EVENT-HEAD-COUNT>");
		sb.append(headCount);
		sb.append("</EVENT-HEAD-COUNT>");

		sb.append("<EVENT-STATUS-IND></EVENT-STATUS-IND>");
		sb.append("<CUSTOMER-ID></CUSTOMER-ID>");
		sb.append("<EVENT-REQUESTOR-INFO>");
		sb.append("<EVENT-REQUESTOR-ORG></EVENT-REQUESTOR-ORG>");
		sb.append("<EVENT-REQUESTOR-NAME></EVENT-REQUESTOR-NAME>");
		sb.append("</EVENT-REQUESTOR-INFO>");
		sb.append("<REQUESTOR-ADDRESS-INFO>");
		sb.append("<ADDR-TYPE-CODE></ADDR-TYPE-CODE>");
		sb.append("<ADDR-STREET-NAME></ADDR-STREET-NAME>");
		sb.append("<ADDR-STREET-NUM></ADDR-STREET-NUM>");
		sb.append("<ADDR-STREET-DIRECTION></ADDR-STREET-DIRECTION>");
		sb.append("<ADDR-APT-SUITE-NUM></ADDR-APT-SUITE-NUM>");
		sb.append("<ADDR-CITY-CODE></ADDR-CITY-CODE>");
		sb.append("<ADDR-STATE-CODE></ADDR-STATE-CODE>");
		sb.append("<ADDR-ZIP-CODE></ADDR-ZIP-CODE>");
		sb.append("</REQUESTOR-ADDRESS-INFO>");
		sb.append("<EVENT-INTERNAL-CONTACT-INFO>");
		sb.append("<EVENT-CONTACT-NAME></EVENT-CONTACT-NAME>");
		sb.append("<EVENT-CONTACT-DEPARTMENT></EVENT-CONTACT-DEPARTMENT>");

		sb.append("<EVENT-CONTACT-LOCATION></EVENT-CONTACT-LOCATION>");
		sb.append("<EVENT-CONTACT-TYPE-CODE></EVENT-CONTACT-TYPE-CODE>");
		sb.append("<EVENT-CONTACT-AREA-CODE>212</EVENT-CONTACT-AREA-CODE>");
		sb.append("<EVENT-CONTACT-EXCHANGE>100</EVENT-CONTACT-EXCHANGE>");
		sb.append("<EVENT-CONTACT-NUMBER>1-866-315-4690</EVENT-CONTACT-NUMBER>");
		sb.append("<EVENT-CONTACT-EXTENSION></EVENT-CONTACT-EXTENSION>");
		sb.append("</EVENT-INTERNAL-CONTACT-INFO>");
		sb.append("<C_COMMENTS></C_COMMENTS>");
		sb.append("<COMMENTS>");
		sb.append("<string></string>");
		sb.append("<string></string>");
		sb.append("<string></string>");
		sb.append("<string></string>");
		sb.append("<string></string>");
		sb.append("<string></string>");
		sb.append("<string></string>");
		sb.append("<string></string>");
		sb.append("<string></string>");
		sb.append("<string></string>");
		sb.append("</COMMENTS>");
		sb.append("<C_CAL-DAY-TYPE-CODE></C_CAL-DAY-TYPE-CODE>");
		sb.append("<CAL-DAY-TYPE-CODE>");
		sb.append("<string></string>");
		sb.append("<string></string>");
		sb.append("<string></string>");
		sb.append("<string></string>");
		sb.append("</CAL-DAY-TYPE-CODE>");
		sb.append("<C_EVENT-COST></C_EVENT-COST>");
		sb.append("<EVENT-COST>");
		sb.append("<EVENT-FEE>");
		sb.append("<decimal></decimal>");
		sb.append("<decimal></decimal>");
		sb.append("<decimal></decimal>");
		sb.append("<decimal></decimal>");
		sb.append("<decimal></decimal>");
		sb.append("<decimal></decimal>");
		sb.append("<decimal></decimal>");
		sb.append("<decimal></decimal>");
		sb.append("<decimal></decimal>");
		sb.append("<decimal></decimal>");
		sb.append("</EVENT-FEE>");
		sb.append("<EVENT-FEE-TYPE-CODE>");
		sb.append("<string></string>");
		sb.append("<string></string>");
		sb.append("<string></string>");
		sb.append("<string></string>");
		sb.append("<string></string>");
		sb.append("<string></string>");
		sb.append("<string></string>");
		sb.append("<string></string>");
		sb.append("<string></string>");
		sb.append("<string></string>");
		sb.append("</EVENT-FEE-TYPE-CODE>");
		sb.append("</EVENT-COST>");
		sb.append("<C_REQUESTOR-PHONE-INFO></C_REQUESTOR-PHONE-INFO>");
		sb.append("<REQUESTOR-PHONE-INFO>");
		sb.append("<PHONE-TYPE-CODE>");
		sb.append("<string></string>");
		sb.append("<string></string>");
		sb.append("<string></string>");
		sb.append("</PHONE-TYPE-CODE>");
		sb.append("<PHONE-AREA-CODE>");
		sb.append("<string></string>");
		sb.append("<string></string>");
		sb.append("<string></string>");
		sb.append("</PHONE-AREA-CODE>");
		sb.append("<PHONE-EXCHANGE>");
		sb.append("<string></string>");
		sb.append("<string></string>");
		sb.append("<string></string>");
		sb.append("</PHONE-EXCHANGE>");
		sb.append("<PHONE-NUMBER>");
		sb.append("<string></string>");
		sb.append("<string></string>");
		sb.append("<string></string>");
		sb.append("</PHONE-NUMBER>");
		sb.append("<PHONE-EXTENSION>");
		sb.append("<string></string>");
		sb.append("<string></string>");
		sb.append("<string></string>");
		sb.append("</PHONE-EXTENSION>");
		sb.append("</REQUESTOR-PHONE-INFO>");
		sb.append("<C_EVENT-REQUIREMENT-INFO></C_EVENT-REQUIREMENT-INFO>");
		sb.append("<EVENT-REQUIREMENT-INFO>");
		sb.append("<EVENT-REQUIREMENT-CODE>");
		sb.append("<string></string>");
		sb.append("<string></string>");
		sb.append("<string></string>");
		sb.append("<string></string>");
		sb.append("<string></string>");
		sb.append("<string></string>");
		sb.append("<string></string>");
		sb.append("<string></string>");
		sb.append("<string></string>");
		sb.append("<string></string>");
		sb.append("<string></string>");
		sb.append("<string></string>");
		sb.append("<string></string>");
		sb.append("<string></string>");
		sb.append("<string></string>");
		sb.append("<string></string>");
		sb.append("<string></string>");
		sb.append("<string></string>");
		sb.append("<string></string>");
		sb.append("<string></string>");
		sb.append("<string></string>");
		sb.append("<string></string>");
		sb.append("<string></string>");
		sb.append("<string></string>");
		sb.append("<string></string>");
		sb.append("</EVENT-REQUIREMENT-CODE>");
		sb.append("<EVENT-REQUIREMENT-QTY>");
		sb.append("<decimal>0</decimal>");
		sb.append("<decimal></decimal>");
		sb.append("<decimal></decimal>");
		sb.append("<decimal></decimal>");
		sb.append("<decimal></decimal>");
		sb.append("<decimal></decimal>");
		sb.append("<decimal></decimal>");
		sb.append("<decimal></decimal>");
		sb.append("<decimal></decimal>");
		sb.append("<decimal></decimal>");
		sb.append("<decimal></decimal>");
		sb.append("<decimal></decimal>");
		sb.append("<decimal></decimal>");
		sb.append("<decimal></decimal>");
		sb.append("<decimal></decimal>");
		sb.append("<decimal></decimal>");
		sb.append("<decimal></decimal>");
		sb.append("<decimal></decimal>");
		sb.append("<decimal></decimal>");
		sb.append("<decimal></decimal>");
		sb.append("<decimal></decimal>");
		sb.append("<decimal></decimal>");
		sb.append("<decimal></decimal>");
		sb.append("<decimal></decimal>");
		sb.append("<decimal></decimal>");
		sb.append("</EVENT-REQUIREMENT-QTY>");
		sb.append("</EVENT-REQUIREMENT-INFO>");
		sb.append("<FAC-EVENT-SCHEDULE>");

		sb.append("<SCHEDULE-KEY>");
		sb.append(eventKey);
		sb.append("</SCHEDULE-KEY>");

		sb.append("<SITE-LOCAL-NUM>");
		sb.append(siteLocalNumber);
		sb.append("</SITE-LOCAL-NUM>");

		sb.append("<LOCATION-NUM></LOCATION-NUM>");

		sb.append("<FACILITY-LOCAL-NUM>");
		sb.append(facilityLocalNumber);
		sb.append("</FACILITY-LOCAL-NUM>");

		sb.append("<INVENTORY-KEY>");
		sb.append(inventoryKey);
		sb.append("</INVENTORY-KEY>");

		sb.append("<SCHEDULE-HEAD-COUNT>");
		sb.append(headCount);
		sb.append("</SCHEDULE-HEAD-COUNT>");

		sb.append("<SCHEDULE-STATUS-IND></SCHEDULE-STATUS-IND>");

		sb.append("<SCHEDULE-START-DATE>");
		sb.append(sdf.format(eventStartDate));
		sb.append("</SCHEDULE-START-DATE>");

		sb.append("<SCHEDULE-END-DATE>");
		sb.append(sdf.format(eventEndDate));
		sb.append("</SCHEDULE-END-DATE>");

		sb.append("<SCHEDULE-START-TIME>");
		sb.append(scheduleStartTime);
		sb.append("</SCHEDULE-START-TIME>");

		sb.append("<SCHEDULE-END-TIME>");
		sb.append(scheduleEndTime);
		sb.append("</SCHEDULE-END-TIME>");

		sb.append("<SCHEDULE-SETUP-TIME></SCHEDULE-SETUP-TIME>");
		sb.append("<SCHEDULE-BREAK-DOWN-TIME></SCHEDULE-BREAK-DOWN-TIME>");
		sb.append("<ROOM-STYLE-SETUP-CODE></ROOM-STYLE-SETUP-CODE>");

		sb.append("<ROOM-CUR-USE-CODE>");
		sb.append(currentRoomUsage);
		sb.append("</ROOM-CUR-USE-CODE>");

		sb.append("<C_SCHEDULE-DAY-CODE></C_SCHEDULE-DAY-CODE>");
		sb.append("<SCHEDULE-DAY-CODE>");
		sb.append("<string></string>");
		sb.append("<string></string>");
		sb.append("<string></string>");
		sb.append("<string></string>");
		sb.append("<string></string>");
		sb.append("<string></string>");
		sb.append("<string></string>");
		sb.append("</SCHEDULE-DAY-CODE>");
		sb.append("<C_REQUESTED-EXCEPTION-DATE></C_REQUESTED-EXCEPTION-DATE>");
		sb.append("<REQUESTED-EXCEPTION-DATE>");
		sb.append("<string></string>");
		sb.append("<string></string>");
		sb.append("<string></string>");
		sb.append("<string></string>");
		sb.append("<string></string>");
		sb.append("<string></string>");
		sb.append("<string></string>");
		sb.append("<string></string>");
		sb.append("<string></string>");
		sb.append("<string></string>");
		sb.append("<string></string>");
		sb.append("<string></string>");
		sb.append("<string></string>");
		sb.append("<string></string>");
		sb.append("<string></string>");
		sb.append("<string></string>");
		sb.append("<string></string>");
		sb.append("<string></string>");
		sb.append("<string></string>");
		sb.append("<string></string>");
		sb.append("</REQUESTED-EXCEPTION-DATE>");
		sb.append("<C_GENERATED-EXCEPTION-DATE></C_GENERATED-EXCEPTION-DATE>");
		sb.append("<GENERATED-EXCEPTION-DATE>");
		sb.append("<string></string>");
		sb.append("<string></string>");
		sb.append("<string></string>");
		sb.append("<string></string>");
		sb.append("<string></string>");
		sb.append("<string></string>");
		sb.append("<string></string>");
		sb.append("<string></string>");
		sb.append("<string></string>");
		sb.append("<string></string>");
		sb.append("<string></string>");
		sb.append("<string></string>");
		sb.append("<string></string>");
		sb.append("<string></string>");
		sb.append("<string></string>");
		sb.append("<string></string>");
		sb.append("<string></string>");
		sb.append("<string></string>");
		sb.append("<string></string>");
		sb.append("<string></string>");
		sb.append("</GENERATED-EXCEPTION-DATE>");
		sb.append("</FAC-EVENT-SCHEDULE>");
		sb.append("</KFR110A1-INPUT>");
		sb.append("</m:KFR110N1>");
		sb.append("</SOAP-ENV:Body>");
		sb.append("</SOAP-ENV:Envelope>");

		return sb.toString();
	}

	// TODO: remove if not used.
	public String getSoapRequest(String siteLocalNumber, String facilityLocalNumber, String inventoryKey,
                                 String eventKey, EventTypeCode eventTypeCode, String eventTitle, Date eventStartDate, Date eventEndDate,
                                 int headCount, List<String> comments, String eventCost, String eventFeeTypeCode,
                                 List<String> eventRequirementCodes, List<Integer> eventRequirementQuantity, String scheduleKey,
                                 int scheduleHeadCount, String scheduleStartTime, String scheduleEndTime, String roomStyleSetupCode,
                                 String roomCurrentUseCode, String scheduleDayCode, List<Date> requestedExceptionDates) {
		return null;
	}
}
