package com.polk.genesis;



import java.text.SimpleDateFormat;
import java.util.Date;

public class SoapSearchRequestBuilder {


	public String getSoapRequest(SearchRequest.USER_ID userId, Date startDate, Date endDate, String startTime, String endTime,
								 String reqDays, int capacity, String campusCenterCode, String builderCodeOrNumber, String roomCodeOrNumber,
								 String setupCode, String stationTypeCode, String useCode, String nextRoomKey) {

		SimpleDateFormat sdf = new SimpleDateFormat("yyyyMMdd");

		StringBuilder sb = new StringBuilder();
		sb.append("<?xml version=\"1.0\" encoding=\"UTF-8\" ?>");
		sb.append("<!-- Generated by Software AG, EntireX Communicator XML Mapping Editor (7.3.3.000) -->");
		sb.append("<SOAP-ENV:Envelope xmlns:SOAP-ENC=\"http://schemas.xmlsoap.org/soap/encoding/\" xmlns:xsi=\"http://www.w3.org/2001/XMLSchema-instance\" xmlns:xmm=\"http://namespace.softwareag.com/entirex/xml/mapping\" xmlns:xsd=\"http://www.w3.org/2001/XMLSchema\" xmlns:SOAP-ENV=\"http://schemas.xmlsoap.org/soap/envelope/\">");
		sb.append("<SOAP-ENV:Header>");
		sb.append("<!-- <SOAPAction>IAL105N1</SOAPAction> -->");
		sb.append("</SOAP-ENV:Header>");
		sb.append("<SOAP-ENV:Body>");
		sb.append("<m:IAL105N1 xmlns:m=\"urn:com-softwareag-entirex-rpc:FCCSCWEB-IAL105N1\">");
		sb.append("<IAL105A1-IN-OUT>");

		sb.append("<USER-ID>");
		sb.append(userId.name());
		sb.append("</USER-ID>");

		sb.append("<START-DATE>");
		sb.append(sdf.format(startDate));
		sb.append("</START-DATE>");

		sb.append("<END-DATE>");
		sb.append(sdf.format(endDate));
		sb.append("</END-DATE>");

		sb.append("<START-TIME>");
		sb.append(startTime);
		sb.append("</START-TIME>");

		sb.append("<END-TIME>");
		sb.append(endTime);
		sb.append("</END-TIME>");

		sb.append("<REQUEST-DAYS>");
		sb.append(reqDays);
		sb.append("</REQUEST-DAYS>");

		sb.append("<REQUEST-CAPACITY>");
		sb.append(capacity);
		sb.append("</REQUEST-CAPACITY>");

		sb.append("<REQUEST-CAMPUS-CENTER>");
		sb.append(campusCenterCode);
		sb.append("</REQUEST-CAMPUS-CENTER>");

		if (builderCodeOrNumber != null && builderCodeOrNumber.trim().length() > 0) {
			sb.append("<REQUEST-BUILDING>");
			sb.append(builderCodeOrNumber);
			sb.append("</REQUEST-BUILDING>");
		}

		if (roomCodeOrNumber != null && roomCodeOrNumber.trim().length() > 0) {
			sb.append("<REQUEST-ROOM>");
			sb.append(roomCodeOrNumber);
			sb.append("</REQUEST-ROOM>");
		}

		if (setupCode != null && setupCode.trim().length() > 0) {
			sb.append("<REQUEST-SETUP-CODE>");
			sb.append(setupCode);
			sb.append("</REQUEST-SETUP-CODE>");
		}

		if (stationTypeCode != null && stationTypeCode.trim().length() > 0) {
			sb.append("<REQUEST-STATION-TYPE>");
			sb.append(stationTypeCode);
			sb.append("</REQUEST-STATION-TYPE>");
		}

		if (useCode != null && useCode.trim().length() > 0) {
			sb.append("<REQUEST-USE-CODE>");
			sb.append(useCode);
			sb.append("</REQUEST-USE-CODE>");
		}

		sb.append("<MUST-BE-SCHEDULER>N</MUST-BE-SCHEDULER>");

		if (nextRoomKey != null && nextRoomKey.trim().length() > 0) {
			sb.append("<NEXT-ROOM-KEY>");
			sb.append(nextRoomKey);
			sb.append("</NEXT-ROOM-KEY>");
		}

		sb.append("</IAL105A1-IN-OUT>");
		sb.append("</m:IAL105N1>");
		sb.append("</SOAP-ENV:Body>");
		sb.append("</SOAP-ENV:Envelope>");

		return sb.toString();
	}

}
