package com.polk.genesis;


public class SoapBookingDeleteRequestBuilder {
	
	public String getSoapRequest(String eventKey) {

		if (eventKey.length() > 9) {
			throw new IllegalArgumentException("Event key can not be more than 9 characters.");
		}

		StringBuilder sb = new StringBuilder();

		sb.append("<?xml version=\"1.0\" encoding=\"UTF-8\"  ?>");
		sb.append("<!-- Generated by Software AG, EntireX XML Mapping Editor (8.0.1.000) on 2015-10-28 at 09:21:54 -->");
		sb.append("<SOAP-ENV:Envelope xmlns:SOAP-ENC=\"http://schemas.xmlsoap.org/soap/encoding/\" xmlns:xsi=\"http://www.w3.org/2001/XMLSchema-instance\" xmlns:xmm=\"http://namespace.softwareag.com/entirex/xml/mapping\" xmlns:xsd=\"http://www.w3.org/2001/XMLSchema\" xmlns:SOAP-ENV=\"http://schemas.xmlsoap.org/soap/envelope/\">");
		sb.append("<SOAP-ENV:Header>");
		sb.append("<!-- <SOAPAction>KFR110N1</SOAPAction> -->");
		sb.append("</SOAP-ENV:Header>");
		sb.append("<SOAP-ENV:Body>");
		sb.append("<m:KFR110N1 xmlns:m=\"urn:com-softwareag-entirex-rpc:PROGDEV-KFR110N1\">");
		sb.append("<KFR110A1-INPUT>");

		sb.append("<EVENT-KEY>");
		sb.append(eventKey);
		sb.append("</EVENT-KEY>");
		sb.append("<CUSTOMER-ID>DELETE</CUSTOMER-ID>");

		sb.append("</KFR110A1-INPUT>");
		sb.append("</m:KFR110N1>");
		sb.append("</SOAP-ENV:Body>");
		sb.append("</SOAP-ENV:Envelope>");

		return sb.toString();
	}

}
